### ISSUE TITLE
GMYLE Bluetooth Dongle Plugged in, still getting "NOT OK. Your hardware doesn't support Bluetooth 4.0"

### ISSUE THREAD

**Issue by holincart** [dokterdok/Continuity-Activation-Tool#278]
I'm on a mid 2010 MacBook pro, running OSX 10.11.2. 

I've got my GMYLE BL 4.0 dongle plugged in, and CAT consistently reports my hardware as not supporting it. The relevant line from running the tool: 

"NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity Current LMP Version=4, expected 6. Aborting."

The diagnostic tool reports the same V=4/expected 6 issue. I've tried this with my system bluetooth turned on and off. The tool will detect when I unplug/replug the dongle, yet it still produces this error.

Am I missing something? What am I doing wrong here? Thanks!

**Comment by sysfloat** [comment]
Open System Information and go to Bluetooth. Whats you LMP Version there?

**Comment by holincart** [comment]
Apple Bluetooth Software Version:	4.4.3f4 16616
  Hardware, Features, and Settings:
  Address:	00-00-00-00-00-00
  Bluetooth Low Energy Supported:	No
  Handoff Supported:	No
  Instant Hot Spot Supported:	No
  Manufacturer:	Ericsson
  Transport:	USB
  Firmware Version:	0.15216 (0.0)
  Bluetooth Power:	Off
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x05AC
  Product ID:	0x8218
  HCI Version:	0x0
  HCI Revision:	0x3B70
  LMP Version:	0x0
  LMP Subversion:	0x00
  Auto Seek Keyboard:	On

**Comment by sysfloat** [comment]
It seems like your dongle is either not correctly recognized or you've got the wrong dongle. Your Manufacturer should be Broadcom.

**Comment by CreativeAnto** [comment]
Will this dongle work with my MacPro 12 Core (Mid 2010) ?

http://www.ebay.com/itm/GMYLE-Ultra-Mini-USB-Broadcom-Bluetooth-Adapter-Dongle-Class-2-V4-0-Dual-Mode-/151811980079?hash=item2358b2fb2f:g:GaMAAOSw~gRV4UMW

I want to buy it today once I know it's the right one and that it will work. I have an ASUS dongle... but no luck with that.


Regards,
Anthony

**Comment by holincart** [comment]
It's definitely the right dongle. After turning off bluetooth in my statusbar, and unplugging/replugging the dongle and looking at the Bluetooth page, it now reads broadcom and LMP version 6:

  Apple Bluetooth Software Version:	4.4.3f4 16616
  Hardware, Features, and Settings:
  Name:	Colin Hart’s MacBook Pro
  Address:	5C-F3-70-71-FA-4A
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	No
  Instant Hot Spot Supported:	No
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	2070B0
  Firmware Version:	v14 c4096
  Bluetooth Power:	Off
  Discoverable:	On
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x0A5C
  Product ID:	0x21E8
  HCI Version:	0x6
  HCI Revision:	0x1000
  LMP Version:	0x6
  LMP Subversion:	0x220E
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On

Going to disable SIP and try this all again.

**Comment by holincart** [comment]
It worked, awesome!

  Apple Bluetooth Software Version:	4.4.3f4 16616
  Hardware, Features, and Settings:
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	Yes
  Instant Hot Spot Supported:	Yes
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	Unknown (ffff)
  Firmware Version:	v14 c4096
  Bluetooth Power:	Off
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x0A5C
  Product ID:	0x21E8
  HCI Version:	0x6
  HCI Revision:	0x1000
  LMP Version:	0x6
  LMP Subversion:	0x220E
  Auto Seek Keyboard:	On

Now to turn Bluetooth back on in the status bar and see if my trackpad and keyboard connect...

**Comment by CreativeAnto** [comment]
Hi Holincart.... I have a MacPro 12 Core (Mid 2010) running El Capitan 11.2.3. I used to have CAT running perfectly on Yosemite with my ASUS Bluetooth 4.0 Dongle, but ever since I upgraded to El Capitan the CAT has been broken.

Could you send me a link to the dongle that you purchased to get CAT to work on El Capitan... and could you tell me where to download the very latest version of the CAT software with all the latest patch updates... and how you can turn SIP off..?


Regards,
Anthony

**Comment by holincart** [comment]
I bought this dongle: http://www.amazon.com/gp/product/B010NISKFK

CAT itself works, after I did the steps I mentioned above. I haven't had the chance to fully determine whether or not continuity itself is operating properly (though the OS lets me activate it now).

The SIP instructions are found in the main readme of this project: 

https://github.com/dokterdok/Continuity-Activation-Tool#cant-open-the-tool

**Comment by mobile4** [comment]
holincart Did you try CAT and GMYLE on 10.11.3?

**Comment by duecedriver** [comment]
I bought a BT dongle off amazon based on the correct 4.0 broadcom chipset.. a UD-400M

it shows the same incompatibility notice as mentioned above.. here is the system profile info with SIP back on and CAT not installed, since it won't.....  apple BT off, dongle plugged in...

product IDs are different.. perhaps it can be added or overridden?


thanks


\  Apple Bluetooth Software Version:	4.4.3f4 16616
  Hardware, Features, and Settings:
  Name: <redaced>
  Address:	<redacted>
  Bluetooth Low Energy Supported:	No
  Handoff Supported:	No
  Instant Hot Spot Supported:	No
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	2046
  Firmware Version:	v208 c522
  Bluetooth Power:	Off
  Discoverable:	On
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x05AC
  Product ID:	0x8213
  HCI Version:	0x4
  HCI Revision:	0x20A
  LMP Version:	0x4
  LMP Subversion:	0x21D0
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On  Apple Bluetooth Software Version:	4.4.3f4 16616
  Hardware, Features, and Settings:
  Name:	<redacted>
  Address:	<redacted>
  Bluetooth Low Energy Supported:	No
  Handoff Supported:	No
  Instant Hot Spot Supported:	No
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	2046
  Firmware Version:	v208 c522
  Bluetooth Power:	Off
  Discoverable:	On
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x05AC
  Product ID:	0x8213
  HCI Version:	0x4
  HCI Revision:	0x20A
  LMP Version:	0x4
  LMP Subversion:	0x21D0
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On

**Comment by mobile4** [comment]
duecedriver What is UD-400M? Is it asus?
When you plug in dongle what is the system profiler info?

**Comment by duecedriver** [comment]
yeah sorry about that .. realized after sending yesterday that even with the bluetooth switched off.. the bluetooth in system reports is the apple board...

here is what shows up in the usb bus...

this is the dongle...

BCM20702A0:

  Product ID:	0x21ec
  Vendor ID:	0x0a5c  (Broadcom Corp.)
  Version:	1.12
  Serial Number:	001986001671
  Manufacturer:	Broadcom Corp
  Location ID:	0x06200000


this is the entire UBS bus hub with apples built in board on it as well... 

USB Bus:

  Host Controller Driver:	AppleUSBOHCIPCI
  PCI Device ID:	0x0aa7 
  PCI Revision ID:	0x00b1 
  PCI Vendor ID:	0x10de 

BCM20702A0:

  Product ID:	0x21ec
  Vendor ID:	0x0a5c  (Broadcom Corp.)
  Version:	1.12
  Serial Number:
  Manufacturer:	Broadcom Corp
  Location ID:	0x06200000

BRCM2046 Hub:

  Product ID:	0x4500
  Vendor ID:	0x0a5c  (Broadcom Corp.)
  Version:	1.00
  Manufacturer:	Apple Inc.
  Location ID:	0x06100000

Bluetooth USB Host Controller:

  Product ID:	0x8213
  Vendor ID:	0x05ac  (Apple Inc.)
  Version:	2.08
  Serial Number:
  Manufacturer:	Apple Inc.
  Location ID:	0x06110000

BCM20702A0:

  Product ID:	0x21ec
  Vendor ID:	0x0a5c  (Broadcom Corp.)
  Version:	1.12
  Serial Number:
  Manufacturer:	Broadcom Corp
  Location ID:	0x06200000

BRCM2046 Hub:

  Product ID:	0x4500
  Vendor ID:	0x0a5c  (Broadcom Corp.)
  Version:	1.00
  Manufacturer:	Apple Inc.
  Location ID:	0x06100000

Bluetooth USB Host Controller:

  Product ID:	0x8213
  Vendor ID:	0x05ac  (Apple Inc.)
  Version:	2.08
  Serial Number:
  Manufacturer:	Apple Inc.
  Location ID:	0x06110000

Bluetooth USB Host Controller:

  Product ID:	0x8213
  Vendor ID:	0x05ac  (Apple Inc.)
  Version:	2.08
  Serial Number:
  Manufacturer:	Apple Inc.
  Location ID:	0x06110000

Thanks

it looks like the dev ID is just a bit off and not loading the kext...

**Comment by mobile4** [comment]
Try to:
Load system without dongle
Switch of bluetooth
Turn of computer
Insert dongle
Turn on computer
Turn on bluetooth
System profiler must show Bluetooth Low energy support - Yes. Handoff and Instant Hotspot are not supported. If you got it - you are ready to apply CAT.

**Comment by duecedriver** [comment]
yeah.. I think that is the problem.. this dongle shows the correct chipset and manufacturer but I think the device/product id is not in the apple bluetooth kext and won't load?  I tired what others have done.. shut off the bluetooth unplug and replug.. but not via reboots..

can you confirm that my device id's are in the apple plist?

**Comment by mobile4** [comment]
I cannot. Basically chipset is important. One more time. When you plug in dongle what does the system profiler say? You have gmyle dongle, haven't you?

**Comment by duecedriver** [comment]
I posted it above..

BCM20702A0:

Product ID: 0x21ec
Vendor ID: 0x0a5c (Broadcom Corp.)
Version: 1.12
Serial Number:
Manufacturer: Broadcom Corp
Location ID: 0x06200000

it shows broadloom

its the correct chipset but the id's have to match what is in apples kexts for them to load for the device.

when bought on amazon it said gmyle but its not on the package.. just that its 4.0 + EDR BCM20702

my guess is that the CAT tool would have to inject the 0x21ec id into the proper kext for it to work.

**Comment by blloyd78** [comment]
I have the same UD-400M dongle and I too cannot get it to work. I spent some time messing around with the BrcmPatchRAM tool ([https://github.com/the-darkvoid/BrcmPatchRAM]), but this didn't seem to do anything either.

I've been through the suggested steps above with no success. Does anyone have any other ideas I can try?

Thanks.

**Comment by duecedriver** [comment]
that 21ec hex is not the device ID that these working broadcom dongles are using and that is expected by the apple kext, hence its not loading... 

with sip we cant just go and exit the kext to insert the new ID since it will no longer pass signing as I understand it.  it must me injected at the time the pre linked kernel in being built but that is beyond my abilities..

for the 10 bucks I wasted probably buying the right one is easiest solution, but given the poor advertising on amazon, I thought this was the right one as someone in the reviews said it was a gymle..

**Comment by blloyd78** [comment]
According to the BrcmPatchRAM site it should be possible to edit that hex value. I couldn't get it to work though.

**Comment by archaik** [comment]
I've installed the listed Broadcom Wi-Fi chip in my 2011 iMac, which previously had Atheros. I cannot get my system to recognize the GBU521 dongle though. I am getting the same line in CAT:

"NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity Current LMP Version=4, expected 6. Aborting."

@mobile4, I've done the steps you listed, but 4.0 is still not loading.

One thing I can think of, I didn't disconnect any wires from the stock bluetooth chip, I only swapped the the Atheros for the Broadcom Wi-Fi, which reads fine.
Is it necessary to disconnect the stock bluetooth wires as well? My system seems to be loading the 2.1 chip instead of the 4.0 dongle.

**Comment by sysfloat** [comment]
@archaik yes disconnecting the old chip should solve this. As you've already concluded, any other connected bluetooth chip/device could cause problems and should therefore be disconnected.

**Comment by archaik** [comment]
Thank you

**Comment by archaik** [comment]
For those still having issues with "NOT OK. Your hardware doesn't support Bluetooth 4.0", this may be of some help. I solved my problem without opening my iMac.

The key was to download the Bluetooth Explorer app from Developer Tools for Xcode, from Apple.
Here's a link to get that done: http://www.geekguides.co.uk/414/how-to-select-a-bluetooth-adapter-in-os-x/

Once you've gone through the steps in the above article and selected your Broadcom Bluetooth dongle, once you restart your Mac, and run system diagnostics for CAT, you should no longer see the "NOT OK" error. As long as you keep the bluetooth dongle plugged in, the Bluetooth Explorer should keep your bluetooth loading to the dongle, not your internal 2.0 bluetooth.

Hopes this helps!

**Comment by duecedriver** [comment]
for me and this particular dongle.. it was not that the original built in bluetooth was blocking activation as my other systems that are osx and dont have bluetooth would fail to load it as a bluetooth device also, stilll points to the device id not loading the kext.. if this tool fixes that it would be easier than having to edit plists and such.. although what kind of overhead is there having to have this tool always running in the background..

**Comment by archaik** [comment]
i don't know if it's a fluke just for me, because i see now the tool says "the change will NOT last after a restart," but to my knowledge, it isn't running in the background, and it DOES keep your desired bluetooth selection after restart. no maintenance required.

worth a shot.

**Comment by archaik** [comment]
nvm. !!! it reverted back on it's own sometime since yesterday. thought it was all good after many restarts.

**Comment by SwedeFlyer** [comment]
I Have a message for deucedriver, please shoot me an email.  Thanks
Swedeflyer@gmail.com

**Comment by dougc84** [comment]
If you, like I, end up getting the UD-400M (marketed as GMYLE, though I don't think it actually is), you've been scammed.  This is a Bluetooth 2.1 device marketed as a 4.0 device.  This is why it will not work.

**Comment by blloyd78** [comment]
Are you sure dougc84? How did you figure that out?

I'll plug mine into a Windows PC tomorrow and see what it detected.

**Comment by blloyd78** [comment]
OK, as promised I have plugged my UD-400M into a Windows PC and it definitely:
- Works
- Is a Bluetooth 4.0 device

Any other ideas out there please?

**Comment by dougc84** [comment]
Then it's a mismatch of drivers.  On OS X, it is reported as a Bluetooth 2.1 device with no low power mode.  It's also branded as + EDR, which does not exist on 4.0.  My guess is there has to be some sort of driver trickery used on certain devices to activate its 4.0 abilities, none of which are available on OS X.

For the record, the IOGEAR one rocks.

**Comment by dubfire** [comment]
UD-400M Same problem, any update for this?

**Comment by YogaFlame** [comment]
I bought the GMYLE from eBay [here ](http://www.ebay.com/itm/301798113872) but I received a USB Bluetooth dongle packaged as a UD-400M. I'm having no luck with Out-of-box compatibility like the folks here. Same problems as described above.. please, somebody tell me they've got it working. I've emailed the seller and even GMYLE about my situation but have yet to hear anything positive back. I hope someone with this dongle has got it working...

It only shows up in my system profile under "USB" as:
BCM20702A0:
  Product ID:	0x21ec
  Vendor ID:	0x0a5c  (Broadcom Corp.)
  Version:	1.12
  Serial Number:	
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Broadcom Corp
  Location ID:	0x1d100000 / 1
  Current Available (mA):	500
  Extra Operating Current (mA):	0



EDIT: I saw on [this page](http://www.insanelymac.com/forum/topic/305945-broadcom-bluetooth-injector/) he listed an Inatek BTA-BC4B6 with the same Product ID & Vendor ID. Is something fishy going on here?

**Comment by airmanchairman** [comment]
@YogaFlame - try cycling Bluetooth on & off in Apple Logo -> System Preferences until you see in Apple Logo -> System Report -> Bluetooth -> Bluetooth Low Energy Supported: YES
Then return to the CAT tool and re-run it;
Failing that, get the Cambridge Silicon Radio (CSR4.0) dongle - its cheap as chips and works for me!

**Comment by YogaFlame** [comment]
Just to update everyone on the GMYLE / UD-400M issue I've had. I've confirmed it does not work on my Mac Pro running Sierra 10.12.1. I got a statement back from GMYLE stating their device is not supported under OSX and they have updated their product descriptions accordingly. Strange... because their site did say it supported OSX (it is now gone).

I looked at the IOGEAR GBU521 but they don't officially support OSX either and although I see people saying it works on El Cap, I don't see anyone saying it works on Sierra so that makes me nervous. @dougc84 - Can you confirm this?

@airmanchairman, if you can recommend a CSR dongle that you know would work on my Early '09 Mac Pro running 10.12.1, please let me know. There's so many different kinds out there and after this experience, I'm wary of taking any kind of purchase risk again.

Thanks

**Comment by dougc84** [comment]
@YogaFlame The IOGEAR GBU521 is what I have, and while it's ugly as sin sticking out of the side of my MacBook, it definitely works.  I'm on 10.12.1, and it works just fine.  Actually, since Sierra came out, Handoff has been even more reliable.

**Comment by NisseA** [comment]
Do you need an airport wifi card to get the GMYLE from eBay to work?

**Comment by albertservices** [comment]
I'm using CSR 4.0 Dongle but it says handoff not supported , what should I do

Apple Bluetooth Software Version:	6.0.7f10
  Hardware, Features, and Settings:
  Name:      MacBook Pro
  Address:	00-1A-7D-DA-71-13
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	No
  Instant Hot Spot Supported:	No
  Manufacturer:	Cambridge Silicon Radio
  Transport:	USB
  Firmware Version:	8891
  Bluetooth Power:	On
  Discoverable:	Off
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x0A12
  Product ID:	0x0001
  HCI Version:	4.0 (0x6)
  HCI Revision:	0x22BB
  LMP Version:	4.0 (0x6)
  LMP Subversion:	0x22BB
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On
